# THIS MODULE CAN BE USED TO CREATE A STRUCTURE THAT MANAGES THE DEVICES IN THE INPUT SOURCE
# SUCH STRUCURES LIKE STATISTIC INFORMATION RETRIEVING, CONTROLING OF INTERNAL ASPECTS OF THE INPUT SOURCES AND DEVICES


class InputSourceSession:
    def __init__(self):
        pass